Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |v|
        v.name = "juddi"
        v.cpus = 2
        v.memory = 1024
    end

    config.vm.network :forwarded_port, guest: 8080, host: 8090

    config.vm.provision :shell, :path => "juddi.sh"

end